version: '3'
services:
  wichteln-mailserver:
    container_name: wichteln-mailserver
    image: greenmail/standalone:1.6.0
    ports:
    - "3025:3025"
    - "3143:3143"
  wichteln-app:
    container_name: wichteln-app
    build: .
    ports:
      - "8080:8080"
    environment:
      MAIL_HOST: wichteln-mailserver
      MAIL_PORT: 3025
      MAIL_USERNAME: testuser
      MAIL_PASSWORD: test_password
      MAIL_PROTOCOL: smtp
    depends_on:
      - wichteln-mailserver