version: '3'
services:
  wichteln-mailserver:
    container_name: wichteln-mailserver
    image: greenmail/standalone:1.6.0
    ports:
      - "3025:3025"
      - "3143:3143"
  wichteln-app:
    container_name: wichteln-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_HOST: wichteln-mailserver
      SPRING_MAIL_PORT: 3025
      SPRING_MAIL_USERNAME: testuser
      SPRING_MAIL_PASSWORD: test_password
      SPRING_MAIL_PROTOCOL: smtp
      LOGGING_LEVEL_COM_ROMANBOEHM_WICHTELN: DEBUG
    depends_on:
      - wichteln-mailserver